const ClientImages = [
  require('./client1.png'),
  require('./client2.png'),
  require('./client3.png'),
  require('./client4.png'),
  require('./client5.png'),
  require('./client6.png'),
  require('./client7.png'),
  require('./client8.png'),
  require('./client9.png'),
  require('./client10.png'),
  require('./client11.png'),
  require('./client12.png'),
  require('./client13.png'),
  require('./client14.png'),
  require('./client15.png'),
  require('./client16.png'),
  require('./client17.png'),
  require('./client18.png'),
  require('./client19.png'),
  require('./client20.png'),
  require('./client21.png'),
  require('./client22.png'),
];

export default ClientImages;
